<?php 
 
$pays = [ 
    "Afrique du Sud",
    "Algérie",
    "Allemagne",
    "Arabie saoudite",
    "Argentine",
    "Australie",
    "Autriche",
    "Belgique",
    "Bolivie",
    "Brésil",
    "Bulgarie",
    "Canada",
    "Chili",
    "Chine",
    "Colombie",
    "Corée du Sud",
    "Croatie",
    "Danemark",
    "Égypte",
    "Équateur",
    "Espagne",
    "États-Unis",
    "Finlande",
    "France",
    "Ghana",
    "Grèce",
    "Hongrie",
    "Inde",
    "Indonésie",
    "Irlande",
    "Islande",
    "Israël",
    "Italie",
    "Japon",
    "Kenya",
    "Madagascar",
    "Maroc",
    "Mexique",
    "Nigeria",
    "Norvège",
    "Nouvelle-Zélande",
    "Ouganda",
    "Paraguay",
    "Pays-Bas",
    "Pérou",
    "Philippines",
    "Pologne",
    "Portugal",
    "Roumanie",
    "Royaume-Uni",
    "Sénégal",
    "Serbie",
    "Suède",
    "Suisse",
    "Thaïlande",
    "Tunisie",
    "Turquie",
    "Ukraine",
    "Uruguay",
    "Vietnam"
]; 
 
?>